### ISSUE TITLE
Trying to follow along with the code but encountered multiple omissions and errors in the code

### ISSUE THREAD

**Issue by seanreed1111** [wangn123/MISSU#6]
Hi, I enjoyed reading your paper, but running the code to date has been impossible. 

When I ran  `MISSU_skip_connection.py` I received many errors. 
For example:

 ``` Unet_skipconnection.py", line 69, in forward
    dilate1_out = nonlinearity(self.dilate1(x))
NameError: name 'nonlinearity' is not defined```

and 

```Unet_skipconnection.py", line 141, in __init__
    self.dblock = DACblock(channels=base_channels * 4)
TypeError: __init__() got an unexpected keyword argument 'channels'
```

Look forward to seeing updated code whenever you have the chance.
Thanks!

**Comment by anonymously123456** [comment]
Thank you for your attention. Please make sure your data is in the correct format and I will fix the problem as soon as possible.
