### ISSUE TITLE
2d operations in DACblock and SPPblock

### ISSUE THREAD

**Issue by Omekaago101** [wangn123/MISSU#7]
Your model takes input tensor of dimension BxCxHxWxD but in the DACblock you are performing conv2d operations as well as MaxPool2d operations in the SPPblock. May I know why?
![Screenshot 2023-07-22 010306](https://github.com/wangn123/MISSU/assets/88082580/478b5ff5-b8d6-4df7-83fe-98f34547f498)
![Screenshot 2023-07-22 010344](https://github.com/wangn123/MISSU/assets/88082580/1279dc12-c84f-4b31-b604-a16ddd09880f)

**Comment by clhbbd** [comment]
My personal feeling is this code is a piece of shit.

**Comment by abdulhai1234** [comment]
> 

agree

**Comment by AbdulHaiKarimi** [comment]
clhbbd 

agree
