### ISSUE TITLE
No folder called data

### ISSUE THREAD

**Issue by Omekaago101** [wangn123/MISSU#8]
In the `train.py` file, you imported `from data.BraTS import BraTS`, but there is no data folder. 
![Screenshot 2023-07-22 011513](https://github.com/wangn123/MISSU/assets/88082580/96a6d0ea-af2c-426d-8f74-61db1f3047c2)

**Comment by AbdulHaiKarimi** [comment]
[get it from here](https://github.com/Wenxuan-1119/TransBTS)
